name: Markdown Lint

on:
  pull_request:
    paths:
      - "**/*.md"
      - ".github/workflows/docs-lint.yml"
      - ".markdownlint-cli2.yaml"
  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - ".github/workflows/docs-lint.yml"
      - ".markdownlint-cli2.yaml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: docs-lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: DavidAnson/markdownlint-cli2-action@6b51ade7a9e4a75a7ad929842dd298a3804ebe8b # v23.1.0

