name: Spell Check

on:
  pull_request:
    paths:
      - "**/*.md"
      - ".github/workflows/spellcheck.yml"
      - ".cspell.json"
  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - ".github/workflows/spellcheck.yml"
      - ".cspell.json"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: spellcheck-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: streetsidesoftware/cspell-action@6f3c77c1406bc930f944ba97e9801a22e42caf58 # v9.1.0
        with:
          config: .cspell.json
          files: "**/*.md"

